import BackPack from './backpack.svg'
import Calendar1 from './Calendar-1.svg'
import Calendar from './Calendar.svg'
import CalendarTimeline from './CalendarTimeline.svg'
import ContactUs from './ContactUs.svg'
import Cruise from './cruise.svg'
import Dish from './dish.svg'
import Diving from './diving.svg'
import Earth from './earth.svg'
import Love from './love.svg'
import Luggages from './luggages.svg'
import Map from './map.svg'
import Mini from './mini.svg'
import Mountain from './mountain.svg'
import Park from './park.svg'
import Tent from './tent.svg'
import Tomorrow from './Tomorrow.svg'
import Train from './train.svg'
import Travelers from './travellers.svg'
import UsefulContent from './UsefulContentIcon.svg'
import User from './user.svg'
import Yesterday from './Yesterday.svg'
export {BackPack, Calendar1, Calendar,CalendarTimeline, ContactUs,Cruise,Dish,Diving,Earth,Love,
    Luggages, Map, Mini,Mountain, Park, Tent,Tomorrow,Train,Travelers,UsefulContent,User,Yesterday
}